server:
  port: 8001
spring:
  application:
    name: microservice-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 5
      max-wait-millis: 200
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/resources/mybatis
      additional-exclude: static/**,public/**
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.microservice.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  instance:
    instance-id: microservice-dept-8001-hystrix #显示服务名
    prefer-ip-address: true             #显示真实IP
  client:
    service-url:
      defaultZone: http://micro7001.com:7001/eureka/,http://micro7002.com:7002/eureka/,http://micro7003.com:7003/eureka/

management:
  server:
    port: 8200
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app.name: microservice-dept
  company.name: Billy
  build.artifactId: microservice-dept-provide-8001-hystrix
  build.version: 1.0-SNAPSHOT