server:
    port: 80
spring:
  devtools:
    restart:
      additional-paths: src/main/java/
      enabled: true
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://micro7001.com:7001/eureka/,http://micro7002.com:7002/eureka/,http://micro7003.com:7003/eureka/