server:
  port: 7003
eureka:
  instance:
    hostname: micro7003.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://micro7001.com:7001/eureka/,http://micro7002.com:7002/eureka/
