server:
  port: 7001
eureka:
  instance:
    hostname: micro7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://micro7002.com:7002/eureka/,http://micro7003.com:7003/eureka/
