server:
  port: 7002
eureka:
  instance:
    hostname: micro7002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://micro7001.com:7001/eureka/,http://micro7003.com:7003/eureka/
